// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3v81kYlz_yOuPSAH1dxr631ynIxBmCQ',
    appId: '1:1007820577617:web:9f5dc3a07f711ec3d49170',
    messagingSenderId: '1007820577617',
    projectId: 'restaurant-app-bcac6',
    authDomain: 'restaurant-app-bcac6.firebaseapp.com',
    storageBucket: 'restaurant-app-bcac6.firebasestorage.app',
    measurementId: 'G-9V5PN6K2C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlAFkCSMxyIaOzw90XMxA1jQ3_h5IU0E',
    appId: '1:1007820577617:android:640ffff34e71b4c3d49170',
    messagingSenderId: '1007820577617',
    projectId: 'restaurant-app-bcac6',
    storageBucket: 'restaurant-app-bcac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPIC1gzamsMUuxq2YvrRPMii-AAESHio',
    appId: '1:1007820577617:ios:b4e9d40e36663ac8d49170',
    messagingSenderId: '1007820577617',
    projectId: 'restaurant-app-bcac6',
    storageBucket: 'restaurant-app-bcac6.firebasestorage.app',
    iosBundleId: 'com.example.resturantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPIC1gzamsMUuxq2YvrRPMii-AAESHio',
    appId: '1:1007820577617:ios:b4e9d40e36663ac8d49170',
    messagingSenderId: '1007820577617',
    projectId: 'restaurant-app-bcac6',
    storageBucket: 'restaurant-app-bcac6.firebasestorage.app',
    iosBundleId: 'com.example.resturantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3v81kYlz_yOuPSAH1dxr631ynIxBmCQ',
    appId: '1:1007820577617:web:22c48f030470b2f6d49170',
    messagingSenderId: '1007820577617',
    projectId: 'restaurant-app-bcac6',
    authDomain: 'restaurant-app-bcac6.firebaseapp.com',
    storageBucket: 'restaurant-app-bcac6.firebasestorage.app',
    measurementId: 'G-B45X0G8B78',
  );
}
